---
# tasks file for deploy-bluegreen

- name: verificando o cantainer que esta no ar
  stat:
   path: /etc/nginx/sites-enabled/green.conf
  register: vhost

- name: copiando o site blue
  copy:
   src: "{{jenkinsdir}}/deploy/index.html" 
   dest: "{{dockerdir}}/blue/_data/index.html"
  when: vhost.stat.exists == True

- name: Copiando o site green
  copy:
   src: "{{jenkinsdir}}/deploy/index.html"
   dest: "{{dockerdir}}/green/_data/index.html"
  when: vhost.stat.exists == False

- name: pegando o ip do container green 
  shell: "docker exec green hostname -I"
  register: ipgreen
  when: vhost.stat.exists == False

- name: pegando o ip do container blue
  shell: "docker exec blue hostname -I"
  register: ipblue
  when: vhost.stat.exists == True

- name: criando o vhost do green
  template:
   src: templates/vhost_green
   dest: /etc/nginx/sites-enabled/green.conf
  when: vhost.stat.exists == False

- name: criando o vhost do blue
  template:
   src: templates/vhost_blue
   dest: /etc/nginx/sites-enabled/blue.conf
  when: vhost.stat.exists == True

- name: apagando o ambiente green
  file:
   path: /etc/nginx/sites-enabled/green.conf
   state: absent
  when: vhost.stat.exists == True

- name: apagando o ambiente blue
  file:
   path: /etc/nginx/sites-enabled/blue.conf
   state: absent
  when: vhost.stat.exists == False

- name: realizando o restart no nginx
  service:
   name: nginx
   state: restarted

